name: Bug report
description: Report a problem or any unexpected behaviors.
title: "[Bug]: "
labels:
  - bug
assignees:
  - BlueGuyEntertainment
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Please explain what happened, and what you expected to happen.
        If you can have any idea what it was caused by and how to reproduce it, that would be helpful as well - include detailed steps if applicable.

        Drag any relevant screenshots or short clips into this textbox.
      placeholder: I'm never gaining any speed when going through the speedboost in
        Easy 09, I would expect it to give me the speed it says it gives. (small
        gif)
    validations:
      required: true
  - type: input
    id: gameversion
    attributes:
      label: Game Version
      description: What version of Wobbler are you running? Feel free to write
        "Latest" if unsure and on latest at the time of posting the issue.
      placeholder: v0.2.1
    validations:
      required: true
  - type: input
    id: osversion
    attributes:
      label: Operating System & Version
      description: e.g. Windows 10 v10.0.19045 | MacOS Ventura 13.6.9 | Linux - Ubuntu 24.04.1
    validations:
      required: true
  - type: input
    id: hardwareinfo
    attributes:
      label: CPU & GPU info
      description: |
        e.g. Intel i5-8400 & Nvidia GTX 1070.
        If on Mac or unsure, try to provide your computer's model name/model number.
        Feel free to include any extra hardware info you feel is relevant.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This probably isn't necessary for most bug reports, unless it's a really severe/weird bug.
        Feel free to also simply upload the log into this textbox if you're not sure.

        Here's where log files can be found:
        Windows: %localappdata%Low\Blue Guy Entertainment Inc\Wobbler\Player.log
        Linux: ~/.config/unity3d/BlueGuyEntertainmentInc/Wobbler/Player.log
        macOS: ~/Library/Logs/Blue Guy Entertainment Inc/Wobbler/Player.log
      value: |
        ```shell
        Insert your log output here..
        ```
    validations:
      required: false
