name: Crash report
description: Report a game crash.
title: "[Crash]: "
labels:
  - crash
  - bug
assignees:
  - BlueGuyEntertainment
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this crash report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Please let us know what steps led up to the crash or if you have any idea what it was caused by. Include detailed steps if applicable.

        Drag any relevant screenshots or short clips into this textbox.
      placeholder: My game crashes every time I go through a checkpoint, on any level.
    validations:
      required: true
  - type: input
    id: gameversion
    attributes:
      label: Game Version
      description: What version of Wobbler are you running? Feel free to write "Latest" if unsure and on latest at the time of posting the issue.
      placeholder: v0.2.1
    validations:
      required: true
  - type: input
    id: osversion
    attributes:
      label: Operating System & Version
      description: |
        e.g: Windows 10 v10.0.19045 | MacOS Ventura 13.6.9 | Linux - Ubuntu 24.04.1 (exact version number optional, but preferred)
      placeholder: Windows 11
    validations:
      required: true
  - type: input
    id: hardwareinfo
    attributes:
      label: CPU & GPU info
      description: |
        If on Mac or unsure, try to provide your computer's model name/model number.
        Feel free to include any extra hardware info you feel is relevant.
      placeholder: Intel i5-8400 & Nvidia GTX 1070
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        Feel free to also simply upload the log into this textbox if you're not sure.

        Here's where log files can be found:
        Windows: %localappdata%Low\Blue Guy Entertainment Inc\Wobbler\Player.log
        Linux: ~/.config/unity3d/BlueGuyEntertainmentInc/Wobbler/Player.log
        macOS: ~/Library/Logs/Blue Guy Entertainment Inc/Wobbler/Player.log
      placeholder: |
        ```shell
        Insert your log output here..
        ```
      value: |
        ```shell
        Insert your log output here..
        ```
    validations:
      required: true
