name: Crash Report
description: Report a game crash.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this crash report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please let us know what steps led up to the crash or if you have any idea what it was caused by. Drag any relevant screenshots into this textbox.
      placeholder: My game crashes every time I go through a checkpoint.
    validations:
      required: true

  - type: input
    id: gameversion
    attributes:
      label: Game Version
      description: What version of Wobbler are you running? Feel free to write "Latest" if unsure and on latest.
      placeholder: v0.2.1
    validations:
      required: true

  - type: input
    id: osversion
    attributes:
      label: Operating System & Version
      description: e.g. Windows 10 v10.0.19045, MacOS Ventura 13.6.9, Linux - Ubuntu 24.04.1.
      placeholder:
    validations:
      required: true

  - type: input
    id: hardwareinfo
    attributes:
      label: CPU & GPU
      description: e.g. Intel i5-8400 & Nvidia GTX 1070. If on Mac or unsure, try to provide your computer's model name/model number. Feel free to include any extra hardware info you feel is relevant.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        Feel free to also simply upload the log into this textbox if you're not sure.
        Here's where log files can be found:
        Windows: %localappdata%Low\Blue Guy Entertainment Inc\Wobbler\Player.log
        Linux: ~/.config/unity3d/BlueGuyEntertainmentInc/Wobbler/Player.log
        macOS: ~/Library/Logs/Blue Guy Entertainment Inc/Wobbler/Player.log
      render: shell
