name: Feature request
description: Suggest a new feature to be added to Wobbler or to the hub
title: "[Feature]: "
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to provide ideas to improve the game!
  - type: textarea
    id: is-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you'd like to see and how it should work. Feel free to include any additional context, screenshots, or short clips.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered. It's possible there are no existing alternatives.
    validations:
      required: false